data/upgrades.js
It's the only one that's an integer
=> Change 'Advanced Homing Missiles' upgrade range value to string value

data/ships.js
I believe the HWK-290 should have both the Rebel and Scum factions listed in the ships.js?
=> HWK-290 should belong to both Rebel and Scum.

.travis.yml
Sets up CI test runs on Travis for all pull requests.
This will start having an effect when https://github.com/guidokessels/xwing-data/pull/35 is merged.
=> New: Add travis ci config

.gitignore, data/upgrades.js, package.json, schemas/conditions.json, schemas/damage-deck.json, schemas/definitions.json, schemas/pilots.json, schemas/ships.json, schemas/sources.json, schemas/upgrades.json, tests/data.js, tests/schema.js, tests/test-schema.js
Issue/Improvement discussed in https://github.com/guidokessels/xwing-data/issues/18
=> JSON schemas and tests for data

data/upgrades.js, tests/keywords.js, tests/test-keywords.js, tests/test-schema.js, tests/utils.js
This should prevent bugs like the following:
- https://github.com/guidokessels/xwing-data/pull/43/files
- https://github.com/guidokessels/xwing-data/pull/39/files
- https://github.com/guidokessels/xwing-data/commit/6f06ee6912667c9512e37b9a5b922dad6810eeea#diff-ca2205d33cc1adbaecdfc232160d7b0dL3100
=> Add test to validate keywords in card text

data/sources.js
Based on https://www.fantasyflightgames.com/en/news/2017/1/23/boshek/ the rest of Wave 10 is being released on Feb. 2, 2017.
=> New: Wave 10 release date

data/upgrades.js
=> Fix: Inconsistent HTML

data/damage-deck-core-tfa.js
See http://xwing-miniatures.wikia.com/wiki/Critical_Hit_Cards#Blinded_Pilot or https://images-cdn.fantasyflightgames.com/filer_public/2d/cd/2dcd4176-46df-434b-9361-7b490d89ada3/x-wing_faq_v423_high_res.pdf
=> Correct text for TFA Blinded Pilot

data/upgrades.js, schemas/definitions.json, schemas/upgrades.json
Structure:
```js
{
"type": "stats",
"name": "attack|agility|hull|shields|skill|energy",
"value": (int)
}
```
=> New: Add stat modifiers to upgrades

data/upgrades.js
Pretty self-explanatory, I think. Definitely let me know if there are any questions or suggestions.
=> Add several missing upgrade grants

data/upgrades.js
=> added heavyscyk title grants field

README.md
Added derivative project as per #83
=> Adding derivative project to readme

data/sources.js, schemas/definitions.json, schemas/sources.json
This includes the fix from https://github.com/guidokessels/xwing-data/pull/97 and a unit test to prevent it happening again.
=> Ship quantity in contents field should be integer

data/sources.js
This change fixes the format of the X-Wing Expansion ship quantities to match those of other expansions.
=> Changed ship quantity in X-Wing Expansion from String to Integer

data/sources.js
Forgot this in my previous PR.
=> New: C-ROC has been released

data/upgrades.js
=> Fix: Cad Bane grants Bomb slot

tests/integrity.test.js
Updated version of @lvisintini pull request.
Closes https://github.com/guidokessels/xwing-data/pull/51
=> Integrity tests

README.md
[![Build Status](https://travis-ci.org/guidokessels/xwing-data.svg?branch=master)](https://travis-ci.org/guidokessels/xwing-data)
[![npm version](https://img.shields.io/npm/v/xwing-data.svg?style=flat)](https://www.npmjs.com/package/xwing-data)
=> New: Add build status and npm version badges

data/upgrades.js
Thanks for reporting, @FreakyDug.
=> Fix: Typo in Automated Protocols card text

README.md
Adds the awesome R2-D7 bot by @FreakyDug to the projects list.
=> New: Add R2-D7 project

data/sources.js
https://www.fantasyflightgames.com/en/news/2017/10/26/when-crime-pays/
=> New: Guns for Hire has been released

data/upgrades.js, tests/utils.js, tests/xws-spec.test.js
Also added some quick tests to check for duplicate xws ids.
=> Fix: Incorrect XWS id for Chopper astromech

tests/xws-spec.test.js
Quick refactor to get rid of some code.
=> Clean up unit test for finding xws id duplicates

data/sources.js
https://www.fantasyflightgames.com/en/news/2017/12/8/raw-untamed-power/
=> New: Mark Wave 12 and 13 as released

data/ships.js
=> Fix: Remove PWT from TIE Aggressor
